### ISSUE TITLE
weird interaction with 'immer' when setting a state with another libraries object.

### ISSUE THREAD

**Issue by jaguardo** [yezyilomo/state-pool#172]
Started a new project, and saw this error for the first time. Wasn't sure if I upgraded a dependent package or something. 

It seems like Immer is being invoked when state-pool is called to set a state.  I have an example that uses  "@js-joda/core" but I think I have seen it with other libraries.
```
import React from 'react'
import { store } from './store'
import {
  ChronoUnit,
} from "@js-joda/core";
import {immerable} from "immer"

... state-pool store setup...

var LocalTime = require("@js-joda/core").LocalDateTime;
// LocalTime[immerable]=true
store.setState("rightMeow", LocalTime.now().truncatedTo(ChronoUnit.SECONDS)) 
```

If I leave the comment line, commented I get the error below.  If I add the key "immerable" as true for the object, the error goes away... weird.

I'll play around with it some more and see where I get.

```
ERROR
[Immer] produce can only be called on things that are draftable: plain objects, arrays, Map, Set or classes that are marked with '[immerable]: true'. Got '2023-04-04T12:33:09'
    at die (http://192.168.1.47:3000/static/js/bundle.js:18010:11)
    at Immer.produce (http://192.168.1.47:3000/static/js/bundle.js:18671:14)
    at GlobalState.__updateValue (http://192.168.1.47:3000/static/js/bundle.js:50449:38)
    at GlobalState.setValue (http://192.168.1.47:3000/static/js/bundle.js:50418:12)
    at dispatch (http://192.168.1.47:3000/static/js/bundle.js:50896:17)
    at Object.current (http://192.168.1.47:3000/static/js/bundle.js:275:5)
    at tick (http://192.168.1.47:3000/static/js/bundle.js:324:21)
```

**Comment by jaguardo** [comment]
Looks like it is manifested when changing the way the ReactDOM is loaded, to conform with the requirements for React 18.

https://stackoverflow.com/questions/71668256/deprecation-notice-reactdom-render-is-no-longer-supported-in-react-18

Still trying to determine the root cause.

**Comment by jaguardo** [comment]
I eventually got the same error as #179 and was able to solve it by upgrading to state-pool v0.10
